### ISSUE TITLE
[Feature request] "input" event

### ISSUE THREAD

**Issue by KaKi87** [kenan238/reblessed#1]
Hello,

It would be nice to have an [input event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event) for elements inheriting from `Form`, thus triggering the listener's callback each time the element's value is changed.

Thanks

**Comment by kenan238** [comment]
You can check the documentation, is there an event that already does this?

**Comment by KaKi87** [comment]
Oh, you made a wiki, very nice !

No, there are only `submit`, `cancel` and `action`.

**Comment by kenan238** [comment]
Done! Should work now, not tested yet, you can use 'oninput'.

**Comment by KaKi87** [comment]
Actually, the event itself should be named `input` so that the listener would be declared using `on('input')`. Thanks

**Comment by KaKi87** [comment]
There is one other issue : the event is fired before the input's value is actually updated.
For example :
```js
const
    blessed = require('reblessed'),
    screen = blessed.screen({
        smartCSR: true
    }),
    textbox = blessed.textbox({
        parent: screen,
        top: 0,
        inputOnFocus: true,
        border: 'line',
        height: 3
    }),
    text = blessed.text({
        parent: screen,
        top: 4
    });
textbox.on('oninput', () => text.setContent(textbox.content));
screen.render();
textbox.focus();
```
When the event is fired after typing `123`, `textbox.content` will only contain `12`.
Thanks

**Comment by kenan238** [comment]
Done! Please see [this commit](https://github.com/kenan238/reblessed/commit/fadd4361d5a6fe86ac8cccf1249b480583e57f9a)

**Comment by KaKi87** [comment]
Working, thanks !
