### ISSUE TITLE
Are PRs for updating to modern ECMAScript welcome?

### ISSUE THREAD

**Issue by rdeforest** [kenan238/reblessed#11]
I almost did a spit-take when I saw lib/program.js. I know some projects don't like code cleanup PRs so I thought I'd ping you before putting any work into it. :) If you _are_ interested, I would also include Babel automation to avoid breaking projects which rely on `reblessed` not using modern ES features.

Additionally, I'm a big fan of CoffeeScript and would be even happier to send you a PR (or set of PRs if you'd like the changes broken into logical chunks) translating the project into CS (while still producing modern and old ES for those who require it).

I totally understand if this kind of thing isn't a priority of the project.

Thanks for raising `blessed` from the dead!

**Comment by kenan238** [comment]
Yes they are! But no useless updates such as updating a var to let, thanks!

**Comment by kenan238** [comment]
If you would like a CoffeeScript version, please make sure to create a separate directory for that.

**Comment by kenan238** [comment]
Update: I am already starting the refactoring on another branch

**Comment by rdeforest** [comment]
Thanks for the update! I'm deep in another project now, so I won't start anything until after your next major release.
