### ISSUE TITLE
Add more flexibility for table border options

### ISSUE THREAD

**Issue by markabrahams** [kenan238/reblessed#22]
Hi - thanks for your work in keeping this library alive @kenan238!

I'm opening an issue to add flexibility to the management of table borders.  I require features such as trimming the extra border characters drawn at various table edges, eliminating all internal horizontal borders, or eliminating all except one horizontal border below the header row.

My initial proposed solution is to introduce an optional "tableBorder" key to a table's creation options with this structure:

```
tableBorder: {
    top: 'noBorderWithoutSpace' | 'noBorderWithSpace' | 'border',
    bottom: 'noBorderWithoutSpace' | 'noBorderWithSpace' | 'border',
    left: 'noBorderWithoutSpace' | 'noBorderWithSpace' | 'border',
    right: 'noBorderWithoutSpace' | 'noBorderWithSpace' | 'border',
    rows: 'all' | 'headerOnly' | 'none'
}
```

to control these table border options.

I've augmented `table.js` to implement these options, and will raise a PR for this shortly.

**Comment by kenan238** [comment]
Sorry for not replying, school and life is getting in the way, you know?

Anyway, i'll review this and check if its set to commit

**Comment by markabrahams** [comment]
No problems and no apology required @kenan238!  Thanks for quickly merging this - much appreciated!
